@startuml

hide footbox
autoactivate on

participant "Service Client" as sc
participant "Service Server" as ss
participant "Nboard DB" as ndb


autonumber 1 "(0)"
ss -> ndb : 캠페인 코드 유무 확인 요청
ndb --> ss : 캠페인 코드 없는 캠페인 리스트 전달
ss --> sc : 캠페인 리스트 전달(메일/문자)

@enduml